### ISSUE TITLE
Add teacher resource (BJC) to the help page

### ISSUE THREAD

**Issue by brollb** [NetsBlox/netsblox.org#55]

**Comment by hamidzr** [comment]
are you talking about [this](http://bjc.edc.org/bjc-r/course/bjc4nyc_teacher.html)

**Comment by hamidzr** [comment]
@brollb should we another block to this page ? https://netsblox.org/help. What do you think about overwriting `Snap Manual` with this?

**Comment by hamidzr** [comment]
added
