### ISSUE TITLE
privacy policy link

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/netsblox.org#87]
there should be a link from the main website. @brollb where do you think we should put it? 
maybe move the contact info from footer to top navbar and have privacy policy link in the footer.

**Comment by brollb** [comment]
Do you think we have enough for a dedicated "about" page? If so, we might be able to move contact info and NSF mention to that page.

Otherwise, we might be able to change the "contact" info to a button and put a "privacy" button next to it.
